name: Test Python package

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        python: [3.8, 3.9, '3.10', '3.11']

    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python }}
        conda-channels: anaconda, conda-forge
        activate-conda: true

    - name: Install Python dependencies
      run: |
        pip install --upgrade -r requirements.txt -r requirements-dev.txt

    - name: All unit tests
      run: |
        pytest -s test/
